module.exports.founder = require("./founder");
module.exports.contact = require("./contact");
module.exports.category = require("./category");
module.exports.teamcategory = require("./team.category");
module.exports.match = require("./match");
module.exports.tournament = require("./tournament");
module.exports.spoartresult = require('./spoartresult');
module.exports.spoartnews = require("./spoart.news");
module.exports.user =require("./user");
